language: node_js
  - "9"

before_script:
  - npm install -g ganache-cli
  - npm install -g truffle@5.0.0



script:
  - ganache-cli -p 8545 > /dev/null &
  - sleep 5
  - cd ./truffle/ truffle compile
  - cd ./truffle/ truffle migrate --network ganache --reset
